* Installation

#+BEGIN_SRC 
pip install --user --upgrade git+https://github.com/mdjbru-forge/pyensembl
#+END_SRC

* Basic usage

** Get information about the genomes to download

There are two different ways to obtain the genomes information before
downloading the actual data.

*** Search for all genomes under a taxon node (recommended)

If the species of interest can all be found in a given taxon, this is the
preferred choice as the information retrieval is fast:

#+BEGIN_SRC 
pyensembl genomes -t serratia > serratia.genomes.results
#+END_SRC

*** Search available species using a string (not recommended)

This is an alternative method, based on searching first through the names of
available species using a string.

**** Get information about available species

The first step is to get the information about bacteria species available in
EnsemblBacteria:

#+BEGIN_SRC 
pyensembl refresh
#+END_SRC

This will download and save the information in a JSON format in a file
=.pyensembl-bacteria-species.<timestamp>= in your home folder.

One can check the JSON files available locally with:

#+BEGIN_SRC 
pyensembl refresh -c
#+END_SRC

The next steps (search) will automatically use the most recent local JSON file.

**** Search among available species

To search among the available species for a string, use =pyensembl search=. The
string will be searched in the =name= and =display_name= fields
(case-insensitive).

#+BEGIN_SRC 
pyensembl search serratia > search.results
pyensembl search "Serratia marcescens" > search.results2
#+END_SRC

The information about matching species is sent to stdout and can be saved to a
file using the redirection symbol =>=.

**** Retrieve the corresponding genome information

This step can take time as the information is retrieved one genome at a time.

#+BEGIN_SRC 
pyensembl genomes -f search.results2 > genomes.results
#+END_SRC
